<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PersonnelsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $personnels = array(
            array('id' => '3', 'citizen_id' => '3500500417695', 'name_title' => 'อ.ดร.', 'name_th' => 'สมนึก สินธุปวน', 'name_en' => 'Somnuek Sinthupuan', 'position_academic' => 'อาจารย์', 'position_manager' => NULL, 'image_profile' => 'profile-1662145520.png', 'email' => 'somnuk@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 24', 'education' => 'ปร.ด.(วิทยาการคอมพิวเตอร์) หลักสูตรนานาชาติ สถาบันบัณฑิตพัฒนบริหารศาสตร์', 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 19:07:23'),
            array('id' => '4', 'citizen_id' => NULL, 'name_title' => 'รศ.', 'name_th' => 'จักรภพ วงศ์ละคร', 'name_en' => 'Jakrapop Wonglakorn', 'position_academic' => 'รองศาสตราจารย์ (Assoc.Prof.)', 'position_manager' => NULL, 'image_profile' => NULL, 'email' => 'jakrapop@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 17', 'education' => 'วท.ม.(คอมพิวเตอร์ศาสตร์) จุฬาลงกรณ์มหาวิทยาลัย', 'personnel_type' => 'อาจารย์', 'academic_type' => 'ข้าราชการ', 'work_status' => '4', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '5', 'citizen_id' => '3500200687956', 'name_title' => 'นาง', 'name_th' => 'ปราณี กันธิมา', 'name_en' => 'Pranee Kanthima', 'position_academic' => 'เจ้าหน้าที่บริหารงานทั่วไป', 'position_manager' => NULL, 'image_profile' => 'profile-1662145431.png', 'email' => 'pranee@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 11-12', 'education' => 'ศศ.บ.(การจัดการทั่วไป) สหวิทยาลัยล้านนาเชียงใหม่', 'personnel_type' => 'เจ้าหน้าที่', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 19:03:51'),
            array('id' => '6', 'citizen_id' => '3501400608970', 'name_title' => 'นาย', 'name_th' => 'ประทีป สุขสมัย', 'name_en' => 'Prateep Sooksamai', 'position_academic' => 'นักวิชาการโสตทัศนศึกษา', 'position_manager' => NULL, 'image_profile' => 'profile-1662145355.png', 'email' => 'prateep@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 25', 'education' => 'วทบ.(เทคโนโลยีอุตสาหกรรม) มหาวิทยาลัยราชภัฎเชียงใหม่', 'personnel_type' => 'เจ้าหน้าที่', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 19:02:35'),
            array('id' => '7', 'citizen_id' => NULL, 'name_title' => 'อ.', 'name_th' => 'ดำเกิง ชำนาญค้า', 'name_en' => 'Domkerng Chamnanca', 'position_academic' => 'อาจารย์', 'position_manager' => NULL, 'image_profile' => NULL, 'email' => 'domkerng@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 19', 'education' => 'M.S.(Agronomy) University of the Phillippines at Los Hanos,Phil.', 'personnel_type' => 'อาจารย์', 'academic_type' => 'ข้าราชการ', 'work_status' => '4', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '8', 'citizen_id' => '3660800333798', 'name_title' => 'ผศ.ดร.', 'name_th' => 'สนิท สิทธิ', 'name_en' => 'Snit Sitti', 'position_academic' => 'ผู้ช่วยศาสตราจารย์', 'position_manager' => 'ผู้อำนวยการสำนักบริหารและพัฒนาวิชาการ', 'image_profile' => 'profile-1662145252.png', 'email' => 'snit@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 15', 'education' => 'ศษ.ด.(เทคโนโลยีการศึกษา) มหาวิทยาลัยเกษตรศาสตร์', 'personnel_type' => 'อาจารย์', 'academic_type' => 'ข้าราชการ', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 19:00:52'),
            array('id' => '9', 'citizen_id' => '3589900025130', 'name_title' => 'ผศ.', 'name_th' => 'ก่องกาญจน์ ดุลยไชย', 'name_en' => 'Kongkarn Dullayachai', 'position_academic' => 'ผู้ช่วยศาสตราจารย์', 'position_manager' => 'เลขานุการหลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์', 'image_profile' => 'profile-1662145176.png', 'email' => 'kongkarn@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 14', 'education' => 'วท.ม.(วิทยาการคอมพิวเตอร์) สถาบันบัณฑิตพัฒนบริหารศาสตร์', 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:59:36'),
            array('id' => '10', 'citizen_id' => NULL, 'name_title' => 'อ.', 'name_th' => 'ชลิตดา มัธยมบุรุษ', 'name_en' => 'Chalitda Madhyamapurush', 'position_academic' => 'อาจารย์', 'position_manager' => 'รองผู้อำนวยการสถาบันบ่มเพาะวิสาหกิจ', 'image_profile' => NULL, 'email' => 'mchalitda@gmail.com', 'tel_number' => '053-873890-93 ต่อ 26', 'education' => 'M.S.(Computer Science) University of North Texas.', 'personnel_type' => 'อาจารย์', 'academic_type' => 'ข้าราชการ', 'work_status' => '3', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '11', 'citizen_id' => '3509900310152', 'name_title' => 'อ.', 'name_th' => 'อลงกต กองมณี', 'name_en' => 'Alongkot Gongmanee', 'position_academic' => 'อาจารย์', 'position_manager' => 'อาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์', 'image_profile' => 'profile-1662145085.png', 'email' => 'alongkot@mju.ac.th', 'tel_number' => '053-873890 ต่อ 22', 'education' => 'M.S.(Information Systems Management)  Ferris State University, U.S.A.', 'personnel_type' => 'อาจารย์', 'academic_type' => 'ข้าราชการ', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:58:05'),
            array('id' => '12', 'citizen_id' => NULL, 'name_title' => 'อ.', 'name_th' => 'ไตรภพ ยศราช', 'name_en' => 'Triphop Yosraj', 'position_academic' => 'พนักงานมหาวิทยาลัย ตำแหน่ง อาจารย์', 'position_manager' => 'ผู้ช่วยคณบดีคณะวิทยาศาสตร์', 'image_profile' => NULL, 'email' => 'triphop@mju.ac.th', 'tel_number' => '053-873560-8 ต่อ 16', 'education' => 'วท.ม.(วิทยาการคอมพิวเตอร์) มหาวิทยาลัยเชียงใหม่ ', 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '3', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '13', 'citizen_id' => '3509900141059', 'name_title' => 'อ.ดร.', 'name_th' => 'กิตติกร หาญตระกูล', 'name_en' => 'Kittikorn Hantrakul', 'position_academic' => 'อาจารย์', 'position_manager' => 'ประธานอาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชานวัตกรรมเทคโนโลยีดิจิทัล, รองผู้อำนวยการสำนักบริหารและพัฒนาวิชาการ', 'image_profile' => 'profile-1662144987.png', 'email' => 'kittikor@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 21', 'education' => 'ปร.ด.(การบริหารเทคโนโลยี) มหาวิทยาลัยแม่โจ้', 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:56:27'),
            array('id' => '14', 'citizen_id' => '3520100840183', 'name_title' => 'อ.', 'name_th' => 'อรรถวิท ชังคมานนท์', 'name_en' => 'Attawit Changkamanon', 'position_academic' => 'อาจารย์', 'position_manager' => 'ประธานอาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์', 'image_profile' => 'profile-1662144873.png', 'email' => 'attawit@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 13', 'education' => 'วท.ม.(วิทยาการคอมพิวเตอร์) มหาวิทยาลัยเชียงใหม่', 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:54:33'),
            array('id' => '15', 'citizen_id' => '1509900290333', 'name_title' => 'ผศ.', 'name_th' => 'ภานุวัฒน์ เมฆะ', 'name_en' => 'Panuwat Mekha', 'position_academic' => 'ผู้ช่วยศาสตราจารย์', 'position_manager' => 'รองประธานอาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์', 'image_profile' => 'profile-1662144788.png', 'email' => 'panuwat_m@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 20', 'education' => 'วท.ม.(วิทยาการคอมพิวเตอร์) มหาวิทยาลัยเชียงใหม่', 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:53:08'),
            array('id' => '18', 'citizen_id' => '3570700560521', 'name_title' => 'นางสาว', 'name_th' => 'พัชรี ยางยืน', 'name_en' => 'Phatcharee Yangyuen', 'position_academic' => 'นักวิชาการคอมพิวเตอร์ชำนาญการ', 'position_manager' => NULL, 'image_profile' => 'profile-1662144696.png', 'email' => 'patcha.y@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 22', 'education' => 'วทม.(เทคโนโลยีสารสนเทศและการจัดการ)มหาวิทยาลัยเชียงใหม่', 'personnel_type' => 'เจ้าหน้าที่', 'academic_type' => 'ข้าราชการ', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:51:36'),
            array('id' => '19', 'citizen_id' => '3509900691270', 'name_title' => 'นางสาว', 'name_th' => 'สุภาพรรณ อนุตรกุล', 'name_en' => 'Suphaphan Anuttarakun', 'position_academic' => 'นักวิชาการคอมพิวเตอร์', 'position_manager' => NULL, 'image_profile' => 'profile-1662144567.png', 'email' => 'supapun@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 23', 'education' => 'วทม.(เทคโนโลยีสารสนเทศและการจัดการ) มหาวิทยาลัยเชียงใหม่', 'personnel_type' => 'เจ้าหน้าที่', 'academic_type' => 'ข้าราชการ', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:49:27'),
            array('id' => '20', 'citizen_id' => '3660800333836', 'name_title' => 'นางสาว', 'name_th' => 'ช่อทิพย์ สิทธิ', 'name_en' => 'Chorthip Sitti', 'position_academic' => 'นักวิชาการคอมพิวเตอร์', 'position_manager' => NULL, 'image_profile' => 'profile-1662144448.png', 'email' => 'chorthip_s@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 25', 'education' => 'วทม.(เทคโนโลยีสารสนเทศและการจัดการ) มหาวิทยาลัยเชียงใหม่', 'personnel_type' => 'เจ้าหน้าที่', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:47:28'),
            array('id' => '51', 'citizen_id' => NULL, 'name_title' => 'นาย', 'name_th' => 'เผด็จ สอนยศ', 'name_en' => 'Padet Sornyot', 'position_academic' => NULL, 'position_manager' => NULL, 'image_profile' => NULL, 'email' => NULL, 'tel_number' => NULL, 'education' => NULL, 'personnel_type' => 'เจ้าหน้าที่', 'academic_type' => NULL, 'work_status' => '4', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '52', 'citizen_id' => NULL, 'name_title' => 'นาย', 'name_th' => 'รศ.จรัส กาใหญ่', 'name_en' => 'Jaras Kayai', 'position_academic' => 'รองศาสตราจารย์ (Assoc.Prof.)', 'position_manager' => NULL, 'image_profile' => NULL, 'email' => NULL, 'tel_number' => NULL, 'education' => NULL, 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '4', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '53', 'citizen_id' => NULL, 'name_title' => 'รศ.', 'name_th' => 'รังสิต ศิริรังษี', 'name_en' => 'Rungsit Sirirungsri', 'position_academic' => 'รองศาสตราจารย์ (Assoc.Prof.)', 'position_manager' => NULL, 'image_profile' => NULL, 'email' => NULL, 'tel_number' => NULL, 'education' => NULL, 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '4', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '54', 'citizen_id' => NULL, 'name_title' => 'อ.', 'name_th' => 'ศิริพงษ์ ชัยชนะ', 'name_en' => 'Siripong Chaichana', 'position_academic' => 'อาจารย์', 'position_manager' => NULL, 'image_profile' => NULL, 'email' => NULL, 'tel_number' => NULL, 'education' => NULL, 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '4', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '55', 'citizen_id' => NULL, 'name_title' => 'อ.', 'name_th' => 'สายัณห์ อุ่นนันกาศ', 'name_en' => 'Sayhun Aoonnunkas', 'position_academic' => 'อาจารย์', 'position_manager' => NULL, 'image_profile' => NULL, 'email' => NULL, 'tel_number' => NULL, 'education' => NULL, 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '5', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '57', 'citizen_id' => NULL, 'name_title' => 'อ.', 'name_th' => 'ไชยา ชวชาติ', 'name_en' => 'Chaiya Chawachat', 'position_academic' => 'อาจารย์', 'position_manager' => NULL, 'image_profile' => NULL, 'email' => NULL, 'tel_number' => NULL, 'education' => NULL, 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '3', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '58', 'citizen_id' => NULL, 'name_title' => NULL, 'name_th' => 'no account', 'name_en' => 'no account', 'position_academic' => NULL, 'position_manager' => NULL, 'image_profile' => NULL, 'email' => NULL, 'tel_number' => NULL, 'education' => NULL, 'personnel_type' => 'no account', 'academic_type' => NULL, 'work_status' => '3', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '60', 'citizen_id' => '3709900410899', 'name_title' => 'อ.ดร.', 'name_th' => 'กอบชัย นิยมธรรม', 'name_en' => 'Kobchai Niyomthom', 'position_academic' => 'อาจารย์', 'position_manager' => NULL, 'image_profile' => NULL, 'email' => 'kobchai@mju.ac.th', 'tel_number' => '053-873560 ต่อ 16', 'education' => 'Doctor of Computer Engineering, Northwestern Polytechnic University, U.S.A.', 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '3', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:44:00'),
            array('id' => '61', 'citizen_id' => '3529900125240', 'name_title' => 'ผศ.ดร.', 'name_th' => 'พาสน์ ปราโมกข์ชน', 'name_en' => 'Part Pramokchon', 'position_academic' => 'ผู้ช่วยศาสตราจารย์', 'position_manager' => 'เลขานุการอาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชานวัตกรรมเทคโนโลยีดิจิทัล', 'image_profile' => 'profile-1662144183.png', 'email' => 'part@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 16', 'education' => 'วศ.ด.(วิศวกรรมคอมพิวเตอร์) มหาวิทยาลัยเกษตรศาสตร์', 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:43:03'),
            array('id' => '63', 'citizen_id' => '3510600688933', 'name_title' => 'ผศ.ดร.', 'name_th' => 'ปวีณ เขื่อนแก้ว', 'name_en' => 'Paween Khoenkaw', 'position_academic' => 'ผู้ช่วยศาสตราจารย์', 'position_manager' => 'รองประธานอาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาวิชานวัตกรรมเทคโนโลยีดิจิทัล', 'image_profile' => 'profile-1662144056.png', 'email' => 'paween_k@mju.ac.th', 'tel_number' => '053-873896', 'education' => 'วศ.ด.(วิศวกรรมคอมพิวเตอร์) มหาวิทยาลัยเกษตรศาสตร์', 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:40:56'),
            array('id' => '64', 'citizen_id' => '1509900130191', 'name_title' => 'อ.ดร.', 'name_th' => 'นษิ ตันติธารานุกุล', 'name_en' => 'Nasi Tantitharanukul', 'position_academic' => 'อาจารย์', 'position_manager' => NULL, 'image_profile' => 'profile-1662143934.png', 'email' => 'nasi@mju.ac.th', 'tel_number' => '053-873890 ต่อ 19', 'education' => 'ปร.ด.(วิศวกรรมคอมพิวเตอร์) มหาวิทยาลัยเชียงใหม่', 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:38:54'),
            array('id' => '65', 'citizen_id' => '3509900816561', 'name_title' => 'อ.ดร.', 'name_th' => 'กิติศักดิ์ โอสถานันต์กุล', 'name_en' => 'Kitisak Osathanunkul', 'position_academic' => 'อาจารย์', 'position_manager' => 'อาจารย์ผู้รับผิดชอบหลักสูตรวิทยาศาสตรบัณฑิต สาขาวิชาวิทยาการคอมพิวเตอร์', 'image_profile' => 'profile-1662143796.png', 'email' => 'kit_o@mju.ac.th', 'tel_number' => '053-873897', 'education' => 'Ph.D.Computer Science, UK.', 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:36:36'),
            array('id' => '66', 'citizen_id' => '3501400030242', 'name_title' => 'อ.ดร.', 'name_th' => 'พยุงศักดิ์ เกษมสำราญ', 'name_en' => 'Payungsak Kasemsumran', 'position_academic' => 'อาจารย์', 'position_manager' => NULL, 'image_profile' => 'profile-1662143257.png', 'email' => 'payungsak_kae@mju.ac.th', 'tel_number' => '053-873890-93 ต่อ 17', 'education' => 'ปร.ด.(วิศวกรรมคอมพิวเตอร์) มหาวิทยาลัยเชียงใหม่', 'personnel_type' => 'อาจารย์', 'academic_type' => 'พนักงานมหาวิทยาลัย', 'work_status' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => '2022-09-02 18:31:58')
        );

        //? Insert $personnels to table
        foreach ($personnels as $personnel) {
            DB::table('personnels')->insert($personnel);
        }
    }
}
