<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubjectsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $subjects = array(
            array('id' => '1', 'subject_code' => '10301111', 'name_th' => 'การเขียนโปรแกรมเบื้องต้น', 'name_en' => 'Fundamentals of Programming', 'detail' => 'กลุ่มวิชาความรู้พื้นฐานทางวิทยาการคอมพิวเตอร์ (Fundamental Computer Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '2', 'subject_code' => '10301112', 'name_th' => 'เทคโนโลยีสารสนเทศและการสื่อสาร', 'name_en' => 'Information and Communications Technology ', 'detail' => 'กลุ่มวิชาความรู้พื้นฐานทางวิทยาการคอมพิวเตอร์ (Fundamental Computer Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => '1', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '3', 'subject_code' => '10301114', 'name_th' => 'องค์ประกอบและสถาปัตยกรรมคอมพิวเตอร์   ', 'name_en' => 'Computer Organization and Architecture', 'detail' => 'กลุ่มวิชาความรู้พื้นฐานทางวิทยาการคอมพิวเตอร์ (Fundamental Computer Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => '2', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '4', 'subject_code' => '10301115', 'name_th' => 'การสร้างเนื้อหาดิจิทัล', 'name_en' => 'Digital Content Creation', 'detail' => 'กลุ่มวิชาความรู้พื้นฐานทางวิทยาการคอมพิวเตอร์ (Fundamental Computer Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '5', 'subject_code' => '10301141', 'name_th' => 'เครือข่ายคอมพิวเตอร์เบื้องต้น', 'name_en' => 'Introduction to Computer Network ', 'detail' => 'กลุ่มวิชาระบบเครือข่าย (Network System)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => '2', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '6', 'subject_code' => '10301212', 'name_th' => 'การเขียนโปรแกรมและทักษะการแก้ปัญหา  ', 'name_en' => 'Programming and Problem Solving Skills', 'detail' => 'กลุ่มวิชาความรู้พื้นฐานทางวิทยาการคอมพิวเตอร์ (Fundamental Computer Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '2', 'self_hour' => '5', 'term' => '2', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '7', 'subject_code' => '10301221', 'name_th' => 'การวิเคราะห์และออกแบบเชิงวัตถุ', 'name_en' => 'Object Oriented Analysis and Design', 'detail' => 'กลุ่มวิชาแนวคิดการวิเคราะห์และออกแบบ (System Analysis)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => '4', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '8', 'subject_code' => '10301222', 'name_th' => 'โครงสร้างข้อมูลและอัลกอริทึม', 'name_en' => 'Data Structure and Algorithm ', 'detail' => 'กลุ่มวิชาแนวคิดการวิเคราะห์และออกแบบ (System Analysis)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => '3', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '9', 'subject_code' => '10301223', 'name_th' => 'ฐานข้อมูลโครงสร้างเชิงสัมพันธ์', 'name_en' => 'Structure Relational  Database', 'detail' => 'กลุ่มวิชาแนวคิดการวิเคราะห์และออกแบบ (System Analysis)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => '3', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '10', 'subject_code' => '10301224', 'name_th' => 'ฐานข้อมูลแบบไม่มีโครงสร้าง', 'name_en' => 'Unstructured Database', 'detail' => 'กลุ่มวิชาแนวคิดการวิเคราะห์และออกแบบ (System Analysis)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => '4', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '11', 'subject_code' => '10301231', 'name_th' => 'เว็บเทคโนโลยี', 'name_en' => 'Web Technology', 'detail' => 'กลุ่มวิชาการพัฒนาระบบแอปพลิเคชัน (Application Development)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => '3', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '12', 'subject_code' => '10301232', 'name_th' => 'การพัฒนาระบบฝั่งเซิร์ฟเวอร์', 'name_en' => 'Server-side  System Development', 'detail' => 'กลุ่มวิชาการพัฒนาระบบแอปพลิเคชัน (Application Development)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => '4', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '13', 'subject_code' => '10301233', 'name_th' => 'การพัฒนาซอฟต์แวร์บนอุปกรณ์เคลื่อนที่', 'name_en' => 'Software Development on Mobile Device', 'detail' => 'กลุ่มวิชาการพัฒนาระบบแอปพลิเคชัน (Application Development)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => '4', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '14', 'subject_code' => '10301311', 'name_th' => 'ทฤษฎีการคำนวณ', 'name_en' => 'Theory of Computation', 'detail' => 'กลุ่มวิชาความรู้พื้นฐานทางวิทยาการคอมพิวเตอร์ (Fundamental Computer Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '15', 'subject_code' => '10301312', 'name_th' => 'เทคนิคการเขียนโปรแกรมคอมพิวเตอร์', 'name_en' => 'Computer Programming Techniques', 'detail' => 'กลุ่มวิชาความรู้พื้นฐานทางวิทยาการคอมพิวเตอร์ (Fundamental Computer Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '16', 'subject_code' => '10301313', 'name_th' => 'วิธีการนิวเมอริคัล', 'name_en' => 'Numerical Methods', 'detail' => 'กลุ่มวิชาความรู้พื้นฐานทางวิทยาการคอมพิวเตอร์ (Fundamental Computer Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '17', 'subject_code' => '10301314', 'name_th' => 'หลักการเขียนโปรแกรมเชิงวัตถุ', 'name_en' => 'Principles of Object-Oriented Programming', 'detail' => 'กลุ่มวิชาความรู้พื้นฐานทางวิทยาการคอมพิวเตอร์ (Fundamental Computer Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '18', 'subject_code' => '10301331', 'name_th' => 'การพัฒนาซอฟต์แวร์ทางเกษตรบนอุปกรณ์เคลื่อนที่  ', 'name_en' => 'Mobile Application Development for Agriculture', 'detail' => 'กลุ่มวิชาการพัฒนาระบบแอปพลิเคชัน (Application Development)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '19', 'subject_code' => '10301332', 'name_th' => 'การพัฒนาซอฟต์แวร์บนระบบปฏิบัติการยูนิกซ์', 'name_en' => 'Software Development on Unix Operating System', 'detail' => 'กลุ่มวิชาการพัฒนาระบบแอปพลิเคชัน (Application Development)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '20', 'subject_code' => '10301333', 'name_th' => 'การพัฒนาโปรแกรมประยุกต์บนเดสก์ท็อป', 'name_en' => 'Desktop Application Development', 'detail' => 'กลุ่มวิชาการพัฒนาระบบแอปพลิเคชัน (Application Development)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '21', 'subject_code' => '10301334', 'name_th' => 'การพัฒนาแอปพลิเคชันข้ามแพลตฟอร์ม', 'name_en' => 'Cross Platform Application Development', 'detail' => 'กลุ่มวิชาการพัฒนาระบบแอปพลิเคชัน (Application Development)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '22', 'subject_code' => '10301335', 'name_th' => 'การออกแบบรูปแบบสำหรับซอฟต์แวร์', 'name_en' => 'Pattern Design for Software', 'detail' => 'กลุ่มวิชาการพัฒนาระบบแอปพลิเคชัน (Application Development)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '23', 'subject_code' => '10301336', 'name_th' => 'คอมพิวเตอร์กราฟิก', 'name_en' => 'Computer Graphics', 'detail' => 'กลุ่มวิชาการพัฒนาระบบแอปพลิเคชัน (Application Development)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '24', 'subject_code' => '10301341', 'name_th' => 'การเข้ารหัสและความปลอดภัยในเครือข่าย', 'name_en' => 'Cryptography  and Network Security', 'detail' => 'กลุ่มวิชาระบบเครือข่าย (Network System)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '25', 'subject_code' => '10301342', 'name_th' => 'การประมวลผลแบบกลุ่มเมฆ', 'name_en' => 'Cloud Computing', 'detail' => 'กลุ่มวิชาระบบเครือข่าย (Network System)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '26', 'subject_code' => '10301343', 'name_th' => 'การเขียนโปรแกรมเครือข่าย', 'name_en' => 'Network  Programming', 'detail' => 'กลุ่มวิชาระบบเครือข่าย (Network System)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '27', 'subject_code' => '10301344', 'name_th' => 'เครือข่ายคอมพิวเตอร์', 'name_en' => 'Computer  Networks', 'detail' => 'กลุ่มวิชาระบบเครือข่าย (Network System)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '28', 'subject_code' => '10301345', 'name_th' => 'ระบบเครือข่ายไร้สาย', 'name_en' => 'Wireless Networks', 'detail' => 'กลุ่มวิชาระบบเครือข่าย (Network System)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '29', 'subject_code' => '10301346', 'name_th' => 'ระบบปฏิบัติการ  ', 'name_en' => 'Operating System', 'detail' => 'กลุ่มวิชาระบบเครือข่าย (Network System)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '30', 'subject_code' => '10301347', 'name_th' => 'วิศวกรรมการพัฒนาปฏิบัติการบนคลาวด์', 'name_en' => 'Cloud Operation Development Engineering', 'detail' => 'กลุ่มวิชาระบบเครือข่าย (Network System)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '31', 'subject_code' => '10301351', 'name_th' => 'วิทยาการข้อมูล  ', 'name_en' => 'Data Science', 'detail' => 'กลุ่มวิชาวิทยาการข้อมูล (Data Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '32', 'subject_code' => '10301352', 'name_th' => 'โครงสร้างข้อมูลสำหรับการแก้ปัญหาทางด้านมัลติมีเดีย', 'name_en' => 'Data Structure for Solving Multimedia Approach', 'detail' => 'กลุ่มวิชาวิทยาการข้อมูล (Data Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '33', 'subject_code' => '10301353', 'name_th' => 'ฐานข้อมูลเชิงพื้นที่', 'name_en' => 'Spatial  Database', 'detail' => 'กลุ่มวิชาวิทยาการข้อมูล (Data Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '34', 'subject_code' => '10301354', 'name_th' => 'พื้นฐานความรู้ด้านข้อมูลขนาดใหญ่', 'name_en' => 'Big Data Fundamentals', 'detail' => 'กลุ่มวิชาวิทยาการข้อมูล (Data Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '35', 'subject_code' => '10301355', 'name_th' => 'ระบบสนับสนุนการตัดสินใจ  ', 'name_en' => 'Decision Support Systems', 'detail' => 'กลุ่มวิชาวิทยาการข้อมูล (Data Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '36', 'subject_code' => '10301356', 'name_th' => 'ระบบสารสนเทศภูมิศาสตร์เบื้องต้น', 'name_en' => 'Introduction to Geographic Information Systems', 'detail' => 'กลุ่มวิชาวิทยาการข้อมูล (Data Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '37', 'subject_code' => '10301357', 'name_th' => 'ระบบเหมืองข้อมูล', 'name_en' => 'Data Mining', 'detail' => 'กลุ่มวิชาวิทยาการข้อมูล (Data Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '38', 'subject_code' => '10301358', 'name_th' => 'วิศวกรรมข้อมูล', 'name_en' => 'Data Engineering', 'detail' => 'กลุ่มวิชาวิทยาการข้อมูล (Data Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '39', 'subject_code' => '10301361', 'name_th' => 'อินเทอร์เน็ตในทุกสิ่ง', 'name_en' => 'Internet of Things', 'detail' => 'กลุ่มวิชาอินเทอร์เน็ตในทุกสิ่ง (Internet of Things)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '40', 'subject_code' => '10301362', 'name_th' => 'การโปรแกรมด้วยภาษาระดับต่ำ', 'name_en' => 'Low-level Programming Language', 'detail' => 'กลุ่มวิชาอินเทอร์เน็ตในทุกสิ่ง (Internet of Things)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '41', 'subject_code' => '10301363', 'name_th' => 'การออกแบบและการพัฒนาระบบทำงานแบบทันที', 'name_en' => 'Design and Development of Real-Time Systems', 'detail' => 'กลุ่มวิชาอินเทอร์เน็ตในทุกสิ่ง (Internet of Things)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '42', 'subject_code' => '10301364', 'name_th' => 'ตรรกศาสตร์เชิงดิจิทัลและอุปกรณ์อัจฉริยะ', 'name_en' => 'Digital Logic and Smart Device', 'detail' => 'กลุ่มวิชาอินเทอร์เน็ตในทุกสิ่ง (Internet of Things)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '43', 'subject_code' => '10301365', 'name_th' => 'ระบบคอมพิวเตอร์และภาษาแอสเซมบลี', 'name_en' => 'Computer System and Assembly Language Programming', 'detail' => 'กลุ่มวิชาอินเทอร์เน็ตในทุกสิ่ง (Internet of Things)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '44', 'subject_code' => '10301366', 'name_th' => 'วิทยาการสมองกลฝังตัว', 'name_en' => 'Embedded System', 'detail' => 'กลุ่มวิชาอินเทอร์เน็ตในทุกสิ่ง (Internet of Things)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '45', 'subject_code' => '10301367', 'name_th' => 'อิเล็กทรอนิกส์เบื้องต้น', 'name_en' => 'Introduction to Electronic Circuit', 'detail' => 'กลุ่มวิชาปัญญาประดิษฐ์  (Artificial Intelligence)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '46', 'subject_code' => '10301371', 'name_th' => 'ปัญญาประดิษฐ์', 'name_en' => 'Artificial Intelligence', 'detail' => 'กลุ่มวิชาปัญญาประดิษฐ์  (Artificial Intelligence)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '47', 'subject_code' => '10301372', 'name_th' => 'การจำลองโดยคอมพิวเตอร์และการสร้างรูปแบบ', 'name_en' => 'Computer Simulation and Modeling', 'detail' => 'กลุ่มวิชาปัญญาประดิษฐ์  (Artificial Intelligence)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '48', 'subject_code' => '10301373', 'name_th' => 'การประมวลผลเชิงภาพ', 'name_en' => 'Image Processing', 'detail' => 'กลุ่มวิชาปัญญาประดิษฐ์  (Artificial Intelligence)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '49', 'subject_code' => '10301374', 'name_th' => 'การประมวลผลภาษาธรรมชาติ    ', 'name_en' => 'Natural Language Processing', 'detail' => 'กลุ่มวิชาปัญญาประดิษฐ์  (Artificial Intelligence)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '50', 'subject_code' => '10301375', 'name_th' => 'การแยกแยะข้อมูลและการแบ่งกลุ่มข้อมูล', 'name_en' => 'Data Classification and Data Clustering ', 'detail' => 'กลุ่มวิชาปัญญาประดิษฐ์  (Artificial Intelligence)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '51', 'subject_code' => '10301376', 'name_th' => 'การเรียนรู้ของเครื่องจักร', 'name_en' => 'Machine Learning', 'detail' => 'กลุ่มวิชาปัญญาประดิษฐ์  (Artificial Intelligence)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '52', 'subject_code' => '10301377', 'name_th' => 'การเรียนรู้ของเครื่องจักรขั้นสูง', 'name_en' => 'Advanced Machine Learning ', 'detail' => 'กลุ่มวิชาปัญญาประดิษฐ์  (Artificial Intelligence)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '53', 'subject_code' => '10301378', 'name_th' => 'การเรียนรู้เครื่องจักรกลสำหรับโมบายแอปพลิเคชัน', 'name_en' => 'Machine Learning for Mobile Application', 'detail' => 'กลุ่มวิชาความรู้พื้นฐานทางวิทยาการคอมพิวเตอร์ (Fundamental Computer Science)กลุ่มวิชาปัญญาประดิษฐ์  (Artificial Intelligence)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '54', 'subject_code' => '10301379', 'name_th' => 'คอมพิวเตอร์วิทัศน์', 'name_en' => 'Computer Vision   ', 'detail' => 'กลุ่มวิชาการประยุกต์งานด้านธุรกิจ (Computer Science for Business)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '55', 'subject_code' => '10301381', 'name_th' => 'การบริหารโครงการคอมพิวเตอร์', 'name_en' => 'Computer Project Management', 'detail' => 'กลุ่มวิชาการประยุกต์งานด้านธุรกิจ (Computer Science for Business)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '56', 'subject_code' => '10301382', 'name_th' => 'การเป็นผู้ประกอบการทางด้านคอมพิวเตอร์และนวัตกรรม', 'name_en' => 'Innovation and Computer-Based Entrepreneurship', 'detail' => 'กลุ่มวิชาการประยุกต์งานด้านธุรกิจ (Computer Science for Business)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '57', 'subject_code' => '10301383', 'name_th' => 'บล็อกเชน และคริปโทเคอร์เรนซี่', 'name_en' => 'Blockchain and Cryptocurrency', 'detail' => 'กลุ่มวิชาการประยุกต์งานด้านธุรกิจ (Computer Science for Business)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '58', 'subject_code' => '10301384', 'name_th' => 'ระบบธุรกิจอัจฉริยะ  ', 'name_en' => 'Business Intelligence System', 'detail' => 'กลุ่มวิชาการประยุกต์งานด้านธุรกิจ (Computer Science for Business)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '59', 'subject_code' => '10301385', 'name_th' => 'ระบบบริหารสารสนเทศเพื่อการจัดการ', 'name_en' => 'Management Information System', 'detail' => 'กลุ่มวิชาการประยุกต์งานด้านธุรกิจ (Computer Science for Business)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '60', 'subject_code' => '10301391', 'name_th' => 'หัวข้อพิเศษทางวิทยาการคอมพิวเตอร์ 1', 'name_en' => 'Special Topics in Computer Science 1', 'detail' => 'กลุ่มวิชาหัวข้อพิเศษ (Special Topics)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '61', 'subject_code' => '10301392', 'name_th' => 'หัวข้อพิเศษทางวิทยาการคอมพิวเตอร์ 2', 'name_en' => 'Special Topics in Computer Science 2', 'detail' => 'กลุ่มวิชาหัวข้อพิเศษ (Special Topics)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => NULL, 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '62', 'subject_code' => '10301225', 'name_th' => 'วิศวรกรรมซอฟต์แวร์', 'name_en' => 'Software Engineering', 'detail' => 'กลุ่มวิชาแนวคิดการวิเคราะห์และออกแบบ (System Analysis)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => '3', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '63', 'subject_code' => '10301211', 'name_th' => 'คณิตศาสตร์สำหรับวิทยาการคอมพิวเตอร์', 'name_en' => 'Mathematic for Computer Science', 'detail' => 'กลุ่มวิชาความรู้พื้นฐานทางวิทยาการคอมพิวเตอร์ (Fundamental Computer Science)', 'credit' => '3', 'theory_hour' => '2', 'practical_hour' => '3', 'self_hour' => '5', 'term' => '3', 'is_del' => '0', 'created_at' => NULL, 'updated_at' => NULL)
        );

        //? Insert $subjects to table
        foreach ($subjects as $subject) {
            DB::table('subjects')->insert($subject);
        }
    }
}
